#ifndef CLICK_PACKETBATCH_HH
#define CLICK_PACKETBATCH_HH

#include <click/config.h>


#if HAVE_VECTOR
    #include <click/packetbatchvector.hh>

    #define FOR_EACH_PACKET(batch,p)            FOR_EACH_PACKET_VEC(batch->first(),p)
    #define FOR_EACH_PACKET_SAFE(batch,p)       FOR_EACH_PACKET_SAFE_VEC(batch->first(),p)
    #define EXECUTE_FOR_EACH_PACKET             EXECUTE_FOR_EACH_PACKET_VEC
    #define EXECUTE_FOR_EACH_PACKET_UNTIL_DO    EXECUTE_FOR_EACH_PACKET_UNTIL_DO_VEC
    #define EXECUTE_FOR_EACH_PACKET_UNTIL       EXECUTE_FOR_EACH_PACKET_UNTIL_VEC
    #define EXECUTE_FOR_EACH_PACKET_UNTIL_DROP  EXECUTE_FOR_EACH_PACKET_UNTIL_DROP_VEC
    #define EXECUTE_FOR_EACH_PACKET_DROPPABLE   EXECUTE_FOR_EACH_PACKET_DROPPABLE_VEC
    #define EXECUTE_FOR_EACH_PACKET_DROP_LIST   EXECUTE_FOR_EACH_PACKET_DROP_LIST_VEC
    #define EXECUTE_FOR_EACH_PACKET_SPLITTABLE  EXECUTE_FOR_EACH_PACKET_SPLITTABLE_VEC
    #define EXECUTE_FOR_EACH_PACKET_ADD         EXECUTE_FOR_EACH_PACKET_ADD_VEC
    #define CLASSIFY_EACH_PACKET                CLASSIFY_EACH_PACKET_VEC
    #define CLASSIFY_EACH_PACKET_IGNORE         CLASSIFY_EACH_PACKET_IGNORE_VEC
    #define MAKE_BATCH                          MAKE_BATCH_VEC

#else
    #include <click/packetbatchlinkedlist.hh>

    #define FOR_EACH_PACKET(batch,p)            FOR_EACH_PACKET_LL(batch->first(),p)
    #define FOR_EACH_PACKET_SAFE(batch,p)       FOR_EACH_PACKET_SAFE_LL(batch->first(),p)
    #define EXECUTE_FOR_EACH_PACKET             EXECUTE_FOR_EACH_PACKET_LL
    #define EXECUTE_FOR_EACH_PACKET_UNTIL_DO    EXECUTE_FOR_EACH_PACKET_UNTIL_DO_LL
    #define EXECUTE_FOR_EACH_PACKET_UNTIL       EXECUTE_FOR_EACH_PACKET_UNTIL_LL
    #define EXECUTE_FOR_EACH_PACKET_UNTIL_DROP  EXECUTE_FOR_EACH_PACKET_UNTIL_DROP_LL
    #define EXECUTE_FOR_EACH_PACKET_DROPPABLE   EXECUTE_FOR_EACH_PACKET_DROPPABLE_LL
    #define EXECUTE_FOR_EACH_PACKET_DROP_LIST   EXECUTE_FOR_EACH_PACKET_DROP_LIST_LL
    #define EXECUTE_FOR_EACH_PACKET_SPLITTABLE  EXECUTE_FOR_EACH_PACKET_SPLITTABLE_LL
    #define EXECUTE_FOR_EACH_PACKET_ADD         EXECUTE_FOR_EACH_PACKET_ADD_LL
    #define CLASSIFY_EACH_PACKET                CLASSIFY_EACH_PACKET_LL
    #define CLASSIFY_EACH_PACKET_IGNORE         CLASSIFY_EACH_PACKET_IGNORE_LL
    #define MAKE_BATCH                          MAKE_BATCH_LL
#endif

#endif // CLICK_PACKETBATCH_HH